In [ ]:
from tensorflow

In [180]:
import numpy as np

In [181]:
from object_loc_helper import getIUO

In [141]:
width = 1000
height = 500
bb_pred = np.array([100, 100, 900, 900])
bb_gt = np.array([50,50,800,800])

In [183]:
getIUO(np.array([bb_gt]), np.array([bb_pred]))

(array([0.6877193]), array([[100, 100, 800, 800]]))

In [142]:
bb_pred, bb_gt

(array([100, 100, 900, 900]), array([ 50,  50, 800, 800]))

In [151]:
x = np.linspace(0, width-1, width )
y = np.linspace(0, height-1, height )

In [153]:
xt = (y - bb_pred[0]) * (y > bb_pred[0]) * (bb_pred[2] > y)
xb = (bb_pred[2] - y) * (bb_pred[2] > y) * (y > bb_pred[0])
xl = (x - bb_pred[1]) * (x > bb_pred[1]) * (bb_pred[3] > x)
xr = (bb_pred[3] - x) * (bb_pred[3] > x) * (x > bb_pred[1])

In [154]:
xt_ = (y - bb_gt[0]) * (y > bb_gt[0]) * (bb_gt[2] > y)
xb_ = (bb_gt[2] - y) * (bb_gt[2] > y) * (y > bb_gt[0])
xl_ = (x - bb_gt[1]) * (x > bb_gt[1]) * (bb_gt[3] > x)
xr_ = (bb_gt[3] - x) * (bb_gt[3] > x) * (x > bb_gt[1])

In [155]:
X = (xl + xr).reshape(-1,1).dot((xt + xb).reshape(1,-1))
X_ = (xl_ + xr_).reshape(-1,1).dot((xt_ + xb_).reshape(1,-1))

In [156]:
Ih = np.min([xt_, xt], axis=0) + np.min([xb_, xb], axis=0)
Iw = np.min([xl_, xl], axis=0) + np.min([xr_, xr], axis=0)

In [164]:
I = Iw.reshape(-1,1).dot(Ih.reshape(1,-1))

In [168]:
U = X + X_ - I

In [175]:
U[U==0] = 1

In [176]:
IoU = I/U

In [179]:
IoU[IoU.nonzero()]

array([0.6877193, 0.6877193, 0.6877193, ..., 0.6877193, 0.6877193,
       0.6877193])